#!/bin/sh
set -e

TARGET_KERNEL_RELEASE=6.1.99-rt36-rockchip-rk3588

if [ "$1" = remove ] || [ "$1" = purge ]; then
    # Do not-load removed hotplug rules on running systems as well.
    udevadm control --reload-rules 2>/dev/null || true
    if [ -d "/lib/modules/$TARGET_KERNEL_RELEASE" ]; then
        depmod -a "$TARGET_KERNEL_RELEASE" 2>/dev/null || true
    fi
fi

#DEBHELPER#
exit 0
