#!/bin/sh
set -e

TARGET_KERNEL_RELEASE=6.1.99-rt36-rockchip-rk3588

if [ "$1" = remove ] || [ "$1" = deconfigure ]; then
    systemctl stop robopi-fan.service 2>/dev/null || true

    if [ "$(uname -r)" = "$TARGET_KERNEL_RELEASE" ]; then
        modprobe -r robopi-ws2812 2>/dev/null || true
    fi
fi

#DEBHELPER#
exit 0
