#!/bin/bash
# SPDX-License-Identifier: GPL-3.0

set -euo pipefail

# Values come from the unit's EnvironmentFile=/etc/default/robopi-ethernet-static.
INTERFACE="${ETHERNET_INTERFACE:-enP4p65s0}"
STATIC_IP="${ETHERNET_IP:-192.168.13.1/24}"
GATEWAY="${ETHERNET_GATEWAY:-192.168.13.10}"
# "-" (not ":-") so an explicitly emptied ETHERNET_DNS2 stays empty.
DNS1="${ETHERNET_DNS1-223.5.5.5}"
DNS2="${ETHERNET_DNS2-8.8.8.8}"
WAIT_SECONDS="${ETHERNET_WAIT_SECONDS:-30}"
RESOLV_CONF="${RESOLV_CONF_PATH:-/etc/resolv.conf}"

usage() {
    cat <<'EOF'
Usage: robopi-ethernet-static <apply|status|check>

Commands:
  apply   Configure the Windows-facing Ethernet uplink: unmanage the
          interface in NetworkManager, wait for it, set the static address,
          replace the default route, and configure DNS
  status  Show the effective configuration and current link state
  check   Verify connectivity (gateway, public IP, DNS resolution)

Configuration lives in /etc/default/robopi-ethernet-static. The board's
internet exit goes through the Windows host on the other end of the cable.
EOF
}

die() {
    printf 'robopi-ethernet-static: %s\n' "$*" >&2
    exit 1
}

require_command() {
    command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

validate_settings() {
    [ -n "$INTERFACE" ] || die "ETHERNET_INTERFACE must not be empty"
    [ -n "$STATIC_IP" ] || die "ETHERNET_IP must not be empty"
    [[ "$STATIC_IP" == */* ]] || die "ETHERNET_IP must be CIDR (e.g. 192.168.13.1/24): $STATIC_IP"
    [ -n "$GATEWAY" ] || die "ETHERNET_GATEWAY must not be empty"
    [[ "$WAIT_SECONDS" =~ ^[0-9]+$ ]] || die "invalid ETHERNET_WAIT_SECONDS: $WAIT_SECONDS"
}

# The conf.d drop-in keeps NetworkManager away from boot onwards. These two
# commands also release a device NM already grabbed, e.g. when the package is
# installed on a running system or ETHERNET_INTERFACE was changed.
release_from_network_manager() {
    require_command nmcli
    printf 'Asking NetworkManager to leave %s unmanaged\n' "$INTERFACE"
    nmcli general reload >/dev/null 2>&1 || true
    nmcli device set "$INTERFACE" managed no >/dev/null 2>&1 || true
}

wait_for_interface() {
    local elapsed=0
    while ! ip link show "$INTERFACE" >/dev/null 2>&1; do
        if [ "$elapsed" -ge "$WAIT_SECONDS" ]; then
            die "network interface not found: $INTERFACE (waited ${WAIT_SECONDS}s)"
        fi
        sleep 1
        elapsed=$((elapsed + 1))
    done
}

configure_dns() {
    local servers=()
    local server
    [ -n "$DNS1" ] && servers+=("$DNS1")
    [ -n "$DNS2" ] && servers+=("$DNS2")

    if command -v resolvectl >/dev/null 2>&1 && resolvectl status >/dev/null 2>&1; then
        if [ "${#servers[@]}" -gt 0 ]; then
            resolvectl dns "$INTERFACE" "${servers[@]}"
        fi
        resolvectl domain "$INTERFACE" '~.'
        resolvectl flush-caches
        printf 'DNS configured through systemd-resolved on %s\n' "$INTERFACE"
        return 0
    fi

    printf 'robopi-ethernet-static: systemd-resolved unavailable; writing %s\n' "$RESOLV_CONF" >&2
    printf 'robopi-ethernet-static: NetworkManager may rewrite this file when Wi-Fi reconnects; enable systemd-resolved for a stable setup\n' >&2
    # A symlink to a dead resolved stub would leave DNS broken; replace it.
    rm -f "$RESOLV_CONF"
    {
        printf '# Generated by robopi-ethernet-static\n'
        for server in "${servers[@]}"; do
            printf 'nameserver %s\n' "$server"
        done
    } > "$RESOLV_CONF"
    chmod 644 "$RESOLV_CONF"
}

apply_config() {
    [ "${EUID:-$(id -u)}" -eq 0 ] || die "apply must be run as root"
    require_command ip
    validate_settings

    printf 'robopi-ethernet-static: interface=%s ip=%s gateway=%s dns=%s,%s wait=%ss\n' \
        "$INTERFACE" "$STATIC_IP" "$GATEWAY" "$DNS1" "$DNS2" "$WAIT_SECONDS"

    release_from_network_manager
    wait_for_interface

    ip link set dev "$INTERFACE" up
    # This service owns the interface: flush first so re-runs never leave
    # duplicate or stale addresses behind.
    ip -4 addr flush dev "$INTERFACE"
    ip addr add "$STATIC_IP" dev "$INTERFACE"
    ip route replace default via "$GATEWAY" dev "$INTERFACE"
    configure_dns

    printf 'robopi-ethernet-static: uplink applied; run "robopi-ethernet-static check" to verify\n'
}

show_status() {
    require_command ip
    printf 'Effective configuration:\n'
    printf '  Interface: %s\n' "$INTERFACE"
    printf '  Static IP: %s\n' "$STATIC_IP"
    printf '  Gateway:   %s\n' "$GATEWAY"
    printf '  DNS:       %s %s\n' "$DNS1" "$DNS2"

    printf '\nLink state:\n'
    ip -br addr show "$INTERFACE" 2>/dev/null || printf '  interface not present: %s\n' "$INTERFACE"
    printf '\nDefault route:\n'
    ip route show default 2>/dev/null || true

    printf '\nDNS:\n'
    if command -v resolvectl >/dev/null 2>&1 && resolvectl status >/dev/null 2>&1; then
        resolvectl status "$INTERFACE" 2>/dev/null || true
    else
        sed -n '1,10p' "$RESOLV_CONF" 2>/dev/null || true
    fi
}

run_check() {
    require_command ping
    local target failures=0

    printf '\nAddress configuration:\n'
    ip addr show "$INTERFACE" 2>/dev/null || printf '  interface not present: %s\n' "$INTERFACE"
    printf '\nRouting table:\n'
    ip route

    for target in "$GATEWAY" 8.8.8.8 baidu.com; do
        if ping -c 3 -W 2 "$target" >/dev/null 2>&1; then
            printf 'PASS: ping %s\n' "$target"
        else
            printf 'FAIL: ping %s\n' "$target" >&2
            failures=$((failures + 1))
        fi
    done

    [ "$failures" -eq 0 ] || die "$failures of 3 connectivity checks failed"
    printf 'All connectivity checks passed.\n'
}

main() {
    local command="${1:-}"

    case "$command" in
        apply) apply_config ;;
        status) show_status ;;
        check) run_check ;;
        -h|--help|help)
            usage
            exit 0
            ;;
        *)
            usage >&2
            exit 2
            ;;
    esac
}

main "$@"
